apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-run-deployment
spec:
  replicas: 3 #run 3 pods 
  selector:
    matchLabels:
      app: fox-run-app
  template:
    metadata:
      labels:
        app: fox-run-app
    spec:
      containers:
      - name: fox-run-container
        image: kg0529/flask
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fox-run-service
spec:
  type: NodePort
  selector:
    app: fox-run-app
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
